# Generated by Django 5.1.1 on 2024-11-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='auctions.auction')),
            ],
        ),
    ]
